import type { Theme } from './index'

export const creamTheme: Theme = {
  name: '奶油手帐',
  type: 'journal',
  colors: {
    bgPrimary: '#f5f0e3',
    bgSecondary: '#faf6ed',
    bgSidebar: '#f5f0e4',
    bgContent: '#fdfaf2',
    bgCard: '#ffffff',
    textPrimary: '#2c3e50',
    textSecondary: '#85929e',
    clockPrimary: '#2c3e50',
    clockSecondary: '#85929e',
    accent: '#2c3e50',
    accentLight: '#f0ebe0',
    border: '#e8e0d0',
    sidebarText: '#6d7d8e',
    sidebarHover: '#f0ebe0',
    sidebarActive: '#e8e0d0',
    sidebarActiveText: '#2c3e50',
    success: '#a5d6a7',
    warning: '#fff59d',
    danger: '#e57373',
    priorityHigh: '#dc2626',
    priorityMedium: '#f59e0b',
    priorityLow: '#85929e',
    focusGradient: '#c9b99a',
    pomodoroWork: '#2c3e50',
    pomodoroBreak: '#81c784',
    // BlockedPage
    blockedBubbleBg: '#2c3e50',
    blockedBubbleText: '#f9f5eb',
    blockedPulseBg: 'rgba(44, 62, 80, 0.1)',
    blockedWarningBg: '#ef4444',
    blockedChillBg: 'rgba(44, 62, 80, 0.1)',
    blockedChillText: '#5d6d7e',
    blockedChillHoldBg: '#fee2e2',
    blockedChillHoldText: '#b91c1c',
  },
  borderRadius: {
    small: '8px',
    medium: '16px',
    large: '24px',
  },
  shadow: {
    small: '0 2px 8px rgba(44, 62, 80, 0.06)',
    medium: '0 4px 16px rgba(44, 62, 80, 0.08)',
    large: '0 8px 32px rgba(44, 62, 80, 0.1)',
  },
  font: {
    primary: '"Nunito", "Noto Sans SC", "PingFang SC", sans-serif',
    secondary: '"Nunito", "Noto Sans SC", sans-serif',
    heading: '"Nunito", "Noto Sans SC", sans-serif',
    hand: '"Patrick Hand", "ZCOOL KuaiLe", cursive',
  },
  showTexture: true,
  showTape: true,
  textureStyle: 'grid',
}
