import type { Theme } from './index'

export const darkTheme: Theme = {
  name: '暗黑',
  type: 'modern',
  blockedPage: {
    text: 'text-white',
    textSecondary: 'text-gray-400',
    bubbleBg: 'bg-white text-black',
    bubbleTail: 'border-t-white',
    buttonBase: 'bg-white text-black hover:shadow-lg hover:shadow-white/20',
    buttonFill: 'bg-rose-200',
    buttonHoverText: 'text-black',
    pulseBg: 'bg-rose-900/10',
    warningBg: 'bg-red-900',
    chillButtonDefault: 'bg-white/10 text-white/70 hover:bg-white/20',
    chillButtonHolding: 'bg-red-900/50 text-white',
  },
  colors: {
    bgPrimary: '#09090b',
    bgSecondary: '#18181b',
    bgSidebar: '#000000',
    bgContent: '#121214',
    bgCard: '#18181b',
    textPrimary: '#e4e4e7',
    textSecondary: '#71717a',
    clockPrimary: '#fafafa',
    clockSecondary: '#a1a1aa',
    accent: '#fafafa',
    accentLight: '#18181b',
    border: '#27272a',
    sidebarText: '#71717a',
    sidebarHover: '#27272a',
    sidebarActive: '#27272a',
    sidebarActiveText: '#fafafa',
    success: '#34d399',
    warning: '#fbbf24',
    danger: '#f87171',
    priorityHigh: '#f87171',
    priorityMedium: '#fbbf24',
    priorityLow: '#71717a',
    pomodoroWork: '#e8a07a',
    pomodoroBreak: '#7ae8a0',
  },
  borderRadius: {
    small: '8px',
    medium: '12px',
    large: '16px',
  },
  shadow: {
    small: '0 2px 8px rgba(0, 0, 0, 0.5)',
    medium: '0 4px 16px rgba(0, 0, 0, 0.6)',
    large: '0 8px 32px rgba(0, 0, 0, 0.7)',
  },
  font: {
    primary: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    secondary: '"Noto Sans SC", sans-serif',
    heading: '"Noto Sans SC", sans-serif',
  },
  showTexture: false,
  showTape: false,
}
