import type { Theme } from './index'

export const pinkTheme: Theme = {
  name: '莫兰迪粉',
  type: 'journal',
  blockedPage: {
    text: 'text-[var(--text-primary)]',
    textSecondary: 'text-[var(--text-secondary)]',
    bubbleBg: 'bg-[var(--text-primary)] text-[var(--bg-primary)]',
    bubbleTail: 'border-t-[var(--text-primary)]',
    buttonBase:
      'bg-[var(--text-primary)] text-[var(--bg-primary)] hover:shadow-lg',
    buttonFill: 'bg-[var(--accent)]',
    buttonHoverText: 'text-[var(--bg-primary)]',
    pulseBg: 'bg-[var(--accent)]/10',
    warningBg: 'bg-red-500',
    chillButtonDefault:
      'bg-[var(--text-primary)]/10 text-[var(--text-secondary)] hover:bg-[var(--text-primary)]/20',
    chillButtonHolding: 'bg-red-100 text-red-700',
  },
  colors: {
    bgPrimary: '#f2efee',
    bgSecondary: '#fbf8f8',
    bgSidebar: '#fcfaf9',
    bgContent: '#fdfcfc',
    bgCard: '#ffffff',
    textPrimary: '#5d5555',
    textSecondary: '#9c9492',
    clockPrimary: '#6e5d5b',
    clockSecondary: '#8a807e',
    accent: '#d4a5a5',
    accentLight: '#f5eeec',
    border: '#e8e4e2',
    sidebarText: '#8a807e',
    sidebarHover: '#f5eeec',
    sidebarActive: '#ebdcd9',
    sidebarActiveText: '#6e5d5b',
    success: '#7EC699',
    warning: '#F0C78A',
    danger: '#E88A8A',
    priorityHigh: '#E88A8A',
    priorityMedium: '#F0C78A',
    priorityLow: '#7EC699',
    pomodoroWork: '#c9a89a',
    pomodoroBreak: '#9eb0a2',
  },
  borderRadius: {
    small: '8px',
    medium: '16px',
    large: '24px',
  },
  shadow: {
    small: '0 2px 8px rgba(0, 0, 0, 0.04)',
    medium: '0 4px 16px rgba(0, 0, 0, 0.06)',
    large: '0 8px 32px rgba(0, 0, 0, 0.08)',
  },
  font: {
    primary: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    secondary: '"Noto Serif SC", "STSong", serif',
    heading: '"ZCOOL XiaoWei", "Ma Shan Zheng", cursive',
  },
  showTexture: true,
  showTape: true,
}
